openapi: 3.0.0
info:
  title: Badges
  version: '1.0'
  contact: {}
  description: See main doc.
paths:
  /badges/:
    post:
      summary: Create badge user
      operationId: post-users-badge
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  signature:
                    type: string
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  signature:
                    type: string
      tags:
        - Users
      parameters:
        - in: header
          name: Badge-Generator-Authorization
          description: Bearer token.
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                publicKey:
                  type: string
