openapi: 3.0.0
info:
  title: locationTransferGroups.openapi
  version: '1.0'
  contact: {}
  description: Partial OpenAPI doc
tags:
  - name: LocationTransferGroups
paths:
  '/locationTransferGroups/{groupId}':
    get:
      tags:
        - LocationTransferGroups
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  transfers:
                    type: array
                    items:
                      type: string
                required:
                  - transfers
        '404':
          description: Not Found
      description: Get the IDs of the location transfer group's incomplete transfers.
      summary: Get incomplete transfers
      operationId: get-locationTransferGroups-groupId
    parameters:
      - schema:
          type: string
          format: uuid
        name: groupId
        in: path
        required: true