openapi: 3.0.0
info:
  title: notifications.openapi
  version: '1.0'
  contact: {}
paths:
  /notifications/traces:
    get:
      tags: [Notifications]
      summary: List of relevant trace IDs by health department
      operationId: post-locationTransfers
      responses:
        '200':
          description: OK
