openapi: 3.0.0
info:
  title: password.openapi
  version: '1.0'
paths:
  /operators/password/forgot:
    post:
      tags:
        - Operators
      summary: ''
      operationId: post-operators-password-forgot
      responses:
        '204':
          description: No Content
        '403':
          description: Forbidden
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                lang:
                  type: string
  /operators/password/change:
    post:
      tags:
        - Operators
      summary: Request password reset e-mail
      operationId: post-operators-password-change
      responses:
        '204':
          description: No Content
        '403':
          description: Forbidden. The account might have been deactivated.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPassword:
                  type: string
                newPassword:
                  type: string
      description: ''
    parameters: []
  /operators/password/reset:
    post:
      tags:
        - Operators
      summary: ''
      operationId: post-operators-password-reset
      responses:
        '204':
          description: No Content
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                resetId:
                  type: string
                newPassword:
                  type: string
  '/operators/password/reset/{resetId}':
    parameters:
      - schema:
          type: string
        name: resetId
        in: path
        required: true
    get:
      tags:
        - Operators
      summary: Get password reset information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  uuid:
                    type: string
                    minLength: 1
                  operatorId:
                    type: string
                    minLength: 1
                  email:
                    type: string
                    minLength: 1
                  closed:
                    type: boolean
                  createdAt:
                    type: string
                    minLength: 1
                  updatedAt:
                    type: string
                    minLength: 1
                required:
                  - uuid
                  - operatorId
                  - email
                  - closed
                  - createdAt
                  - updatedAt
      operationId: get-operators-password-reset-resetId
      description: ''
tags:
  - name: Operators
