openapi: 3.0.0
info:
  title: Health department employees password
  version: '1.0'
  contact: {}
  description: See main doc.
tags:
  - name: HealthDepartmentEmployees
paths:
  /healthDepartmentEmployees/password/change:
    post:
      tags:
        - HealthDepartmentEmployees
      summary: Change password
      operationId: post-healthDepartmentEmployees-password-change
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
      description: Change password.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPassword:
                  type: string
                newPassword:
                  type: string

              required:
                - currentPassword
                - newPassword
  /healthDepartmentEmployees/password/renew:
    patch:
      tags:
        - HealthDepartmentEmployees
      summary: Renew password of employee
      operationId: patch-healthDepartmentEmployees-password-renew
      responses:
        '200':
          description: Ok
        '403':
          description: Forbidden
      description: Renew password of employee.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                employeeId:
                  type: string

              required:
                - employeeId
