openapi: 3.0.0
info:
  title: Health department employees password
  version: '1.0'
  contact: {}
  description: See main doc.
tags:
  - name: HealthDepartmentEmployees
paths:
  /healthDepartmentEmployees/password/change:
    post:
      tags:
        - HealthDepartmentEmployees
      summary: Change password
      operationId: post-healthDepartmentEmployees-password-change
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized
      description: Change password.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPassword:
                  type: string
                newPassword:
                  type: string

              required:
                - currentPassword
                - newPassword